apiVersion: 1

datasources:
  - name: Airflow-Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: airflow
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: StockInsight-MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: stock_insight
    user: stockapp
    secureJsonData:
      password: stockapp
